# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: frozen007 blog
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "/frozen007" # the subpath of the site
url: "https://frozen007.github.io/" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
# google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: About
      slug: /work
    - name: Blog
      slug: /blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: zmy1019@163.com
      link: mailto:zmy1019@163.com
    - name: WeChat
      value: twister1017
      link: "#"
  follow:
    - name: GitHub
      link: http://github.com/frozen007
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
